language: ruby

cache: bundler

rvm:
  - 2.5.0

services:
  - postgresql

env:
  - RAILS_ENV=test DATABASE_URL=postgres://postgres@localhost:5432/postgres

before_script:
  - bin/rails db:setup

script:
  - bin/rails test
