version: '3'
services:
  rails:
    build: .
    command: /bin/sh -c "rm ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
