version: '3'
services:
  rails:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    links:
      - postgres
    volumes:
      - ..:/usr/src/app
  postgres:
    image: postgres:10.3-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
